# Generated by Django 4.1.1 on 2022-10-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(help_text='format: required, max characters:100', max_length=150, verbose_name='section header')),
                ('subheader', models.CharField(help_text='format: required, max characters:100', max_length=150, verbose_name='section header')),
                ('style', models.CharField(choices=[('H', 'Hero'), ('F', 'Featured'), ('C', 'Cities'), ('R', 'Recent'), ('S', 'Scroll')], max_length=1)),
                ('rank', models.IntegerField(default=0, help_text='format: required, higher rank has higher priority', verbose_name='ranking order of homepage')),
            ],
            options={
                'ordering': ('-rank', 'header', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='format: required, derived from article title', max_length=150, verbose_name='article safe URL')),
                ('text', models.CharField(help_text='format: required, max characters:100', max_length=150, verbose_name='link text')),
                ('rank', models.IntegerField(default=0, help_text='format: required, higher rank has higher priority', verbose_name='ranking order of articles')),
                ('homepage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.homepage')),
            ],
            options={
                'ordering': ('-rank', 'text', 'id'),
            },
        ),
    ]
