# Generated by Django 4.1.1 on 2022-10-01 23:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max characters:30', max_length=30, verbose_name='city name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max characters:30', max_length=30, verbose_name='country name')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='format: required, max characters:100', max_length=150, verbose_name='article title')),
                ('slug', models.SlugField(help_text='format: required, derived from article title', max_length=150, verbose_name='article safe URL')),
                ('body', tinymce.models.HTMLField()),
                ('rank', models.IntegerField(default=0, help_text='format: required, higher rank has higher priority', verbose_name='ranking order of articles')),
                ('is_visible', models.BooleanField(default=True, help_text='format: required, default=True, True = Visible False = Not visible', verbose_name='article visible')),
                ('featured_home', models.BooleanField(default=False, help_text='format: required, default=False, True = Visible False = Not visible', verbose_name='article visible on home page')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='articles.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='articles.country')),
            ],
        ),
    ]
