# Generated by Django 4.1.1 on 2022-10-21 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        ('articles', '0002_alter_article_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='homepage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_article', to='frontend.homepage'),
        ),
    ]
